### ISSUE TITLE
Unauthorized user picture copy

### ISSUE THREAD

**Issue by CastagnaIT** [fuxxociety/repository.fuxxociety#1]
@fuxxociety you have copied my scripts and its ok
but you are not allowed to copy my user picture:
https://github.com/fuxxociety/repository.fuxxociety/blob/main/repository.fuxxociety/icon.jpg

I encourage you to remove it as soon as possible

**Comment by fuxxociety** [comment]
Removed all scripts, images, and references to @CastagnaIT
